apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eshop
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ""
      kind: ""
  description: eshop project configuration
  destinations:
    - namespace: eshop
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/J0hn-B/eshop.git
