{{- if not .Values.speaker.secretName }}
apiVersion: v1
data:
  secretkey: {{ randAlphaNum 256 | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "metallb.fullname" . }}-memberlist
  labels: {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: speaker
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
