{{- if .Values.controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metallb.controllerServiceAccountName" . }}
  labels: {{- include "metallb.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.speaker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metallb.speakerServiceAccountName" . }}
  labels: {{- include "metallb.labels" . | nindent 4 }}
{{- end }}
