apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  destination:
    namespace: chaos-testing
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      valueFiles:
      - values.yaml
    path: k8s/k8s-charts/chaos-mesh
    repoURL: https://github.com/J0hn-B/eshop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true