apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-pod-carts
  namespace: eshop
spec:
  action: pod-kill
  mode: one
  value: ""
  duration: "60s"
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  scheduler:
    cron: "@every 2m"