apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      valueFiles:
      - values.yaml
    path: k8s/metrics-server
    repoURL: https://github.com/J0hn-B/k8s-prep.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
