apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      parameters:
      - name: prometheusOperator.admissionWebhooks.failurePolicy
        value: Ignore
      valueFiles:
      - values.yaml
    path: k8s/k8s-charts/kube-prometheus-stack
    repoURL: https://github.com/J0hn-B/eshop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
