{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-state-metrics.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-state-metrics.labels" . | nindent 4 }}
{{- end }}
