apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-cluster-management
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: k8s-config
  source:
    helm:
      valueFiles:
        - values.yaml
    path: k8s-config
    repoURL: https://github.com/J0hn-B/k8s-prep.git
    targetRevision: HEAD
