apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: carts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carts
  minReplicas: 1
  maxReplicas: 3
  metrics:
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 450Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85 
  - type: Pods
    pods:
      metric:
        name: memory
      target:
        type: AverageValue
        averageValue: 450Mi      